# 3-7 Shrinking Guest List
guests = ["Jesus", "Paul", "John", "Peter"]
print(f"I am inviting {len(guests)} guests to my dinner party")
print(f"Hey {guests[0]}, would you like you come to my dinner party?")
print(f"Hey {guests[1]}, would you like you come to my dinner party?")
print(f"Hey {guests[2]}, would you like you come to my dinner party?")
print(f"Hey {guests[3]}, would you like you come to my dinner party?")
print(f"Sadly, {guests[1]} can't make it tonight")
guests = ["Jesus", "Abraham", "John", "Peter"]
print(f"I am inviting {len(guests)} guests to my dinner party")
print(f"Hey {guests[0]}, would you like you come to my dinner party?")
print(f"Hey {guests[1]}, would you like you come to my dinner party?")
print(f"Hey {guests[2]}, would you like you come to my dinner party?")
print(f"Hey {guests[3]}, would you like you come to my dinner party?")
print("We have found a bigger table for the dinner party")
guests.insert(0, "Noah")
guests.append("Adam")
guests.insert(3, "Eve")
print(f"I am inviting {len(guests)} guests to my dinner party")
print(f"Hey {guests[0]}, would you like you come to my dinner party?")
print(f"Hey {guests[1]}, would you like you come to my dinner party?")
print(f"Hey {guests[2]}, would you like you come to my dinner party?")
print(f"Hey {guests[3]}, would you like you come to my dinner party?")
print(f"Hey {guests[4]}, would you like you come to my dinner party?")
print(f"Hey {guests[5]}, would you like you come to my dinner party?")
print(f"Hey {guests[6]}, would you like you come to my dinner party?")
print("The dinner table will not be at the party in time, so I have to invite only 2 guests")
print(f"Sorry {guests.pop()} you are not invited to the dinner party")
print(f"Sorry {guests.pop()} you are not invited to the dinner party")
print(f"Sorry {guests.pop()} you are not invited to the dinner party")
print(f"Sorry {guests.pop()} you are not invited to the dinner party")
print(f"Sorry {guests.pop()} you are not invited to the dinner party")
print(f"I am inviting {len(guests)} guests to my dinner party")
print(f"Hey {guests[0]}, You are still invited to my dinner party")
print(f"Hey {guests[1]}, You are still invited to my dinner party")
del guests[1]
del guests[0]
print(guests)